### ISSUE TITLE
linode_api_token syntax error

### ISSUE THREAD

**Issue by thesammiller** [codingforentrepreneurs/terraforming-kubernetes#1]
Great tutorial. I really enjoyed it and appreciated the balance between depth and speed. 

Ran into a small issue with the command:
`echo "linode_api_token='YOUR_API_KEY'" >> devops/terraform.tfvars`

After installing the VS Code extension for Terraform syntax, the single quotes around YOUR_API_KEY generated an error: 
`Single quotes are invalid. Use double quotes (") to enclose strings.`

Technically, the command should be:
`echo "linode_api_token=\"YOUR_API_KEY\"" >> devops/terraform.tfvars` 

I don't love the escaped double quotes, but since it's a copy-paste example, I was surprised to get the syntax error.

I can submit a PR for this. I thought there may be a conscious choice though so wanted to check first.

**Comment by jmitchel3** [comment]
Thanks Sam! What OS are you on? Double quotes is what I should use and I’ll update shortly.

**Comment by thesammiller** [comment]
Okay, cool. I'm on Debian 11. Thanks again!

**Comment by jmitchel3** [comment]
Thanks again! It’s fixed.
